# Generated by Django 4.2.2 on 2023-06-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriler', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='iha',
            options={'verbose_name': 'IHAlar', 'verbose_name_plural': 'IHAlar'},
        ),
        migrations.RemoveField(
            model_name='iha',
            name='category',
        ),
        migrations.AddField(
            model_name='iha',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Kategori'),
        ),
    ]
